version: "3.8"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - ENV_FILE=.env

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - ENV_FILE=.env
    ports:
      - 3002:3000

  # monitoring:
  #   build:
  #     context: ./monitoring
  #     dockerfile: Dockerfile
  #   environment:
  #     - ENV_FILE=.env
