version: "3"
services:
  node-app:
    build:
      context: ./app
    ports:
      - "3000:3000"
    depends_on:
      - elasticsearch
    volumes:
      - ./app-logs:/src/logs
    networks:
      - devops

  prometheus:
    image: prom/prometheus:v2.48.0-rc.2
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - devops
    depends_on:
      - node-app

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    networks:
      - devops
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # Change this password for security
    depends_on:
      - prometheus

networks:
  devops:
    driver: bridge
