version: "3.8"

services:
  api:
    environment:
      - ENV_FILE=.env.dev
    ports:
      - "3000:3000"
    volumes:
      - ./api:/usr/src/app
    command: npm run dev

  client:
    environment:
      - ENV_FILE=.env.dev
    ports:
      - "3002:3000"
    volumes:
      - ./client:/usr/src/app
    command: npm run dev
